SELECT  SUM(CAB.VLRNOTA) AS VL_NOTAS
       ,COUNT(CAB.NUNOTA) AS QTD_NOTA
       ,SUM(CAB.VLRNOTA)/COUNT(CAB.NUNOTA) AS TICKET
       ,UFS.UF
       ,UFS.DESCRICAO
FROM TGFCAB CAB
JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
JOIN TSICID CID ON PAR.CODCID = CID.CODCID
JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
WHERE CAB.TIPMOV = 'P'  /*P = Pedido de venda*/
  AND CAB.DTNEG BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
  AND (CAB.CODVEND = :P_VENDEDOR OR :P_VENDEDOR IS NULL)
  AND (CAB.STATUSNOTA = 'L' OR :P_CONFIR = 'N')
  AND (TO_CHAR(CAB.DTNEG, 'MONTH/YYYY') = :A_MESANO OR :A_MESANO IS NULL)
GROUP BY UFS.UF
        ,UFS.DESCRICAO
ORDER BY 3 DESC
