SELECT  CAB.NUNOTA
       ,CAB.DTNEG
       ,CAB.VLRNOTA
       ,CASE 
            WHEN :A_TICKET <= CAB.VLRNOTA THEN 1
            WHEN :A_TICKET >  CAB.VLRNOTA THEN 2
            WHEN :A_TICKET IS NULL THEN 3
        END AS ICONE
       ,PAR.CODPARC
       ,PAR.NOMEPARC
       ,UFS.UF
       ,UFS.DESCRICAO
       ,CID.CODICID
       ,CID.NOMECID
       ,VEN.CODVEND
       ,VEN.APELIDO
       ,EMP.CODEMP
       ,EMP.NOMEFANTASIA
FROM TGFCAB CAB
JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
JOIN TSICID CID ON PAR.CODCID = CID.CODCID
JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP
JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
WHERE CAB.TIPMOV = 'P' /*P = Pedido de venda*/
  AND CAB.DTNEG BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
  AND (CAB.CODVEND = :P_VENDEDOR OR :P_VENDEDOR IS NULL)
  AND CAB.CODEMP IN :P_EMPRESA
  AND (CAB.STATUSNOTA = 'L' OR :P_CONFIR = 'N')
  AND (TO_CHAR(CAB.DTNEG, 'MONTH/YYYY') = :A_MESANO OR :A_MESANO IS NULL)
  AND (UFS.UF = :P_UF OR :P_UF IS NULL)
