SELECT 
SUM(CAB.VLRNOTA) AS VL_NOTAS,
COUNT(CAB.VLRNOTA) AS QTD_NOTA,
SUM(CAB.VLRNOTA) / COUNT(CAB.NUNOTA) AS TICKET
FROM TGFCAB CAB
WHERE CAB.TIPMOV = 'P'
  AND CAB.DTNEG BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN