SELECT 
SUM(CAB.VLRNOTA) AS VL_NOTAS,
COUNT(CAB.VLRNOTA) AS QTD_NOTA,
SUM(CAB.VLRNOTA) / COUNT(CAB.NUNOTA) AS TICKET
FROM TGFCAB CAB
WHERE CAB.TIPMOV = 'P'
  AND CAB.DTNEG BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
  AND (CAB.CODVEND = :P_CODVEND OR :P_CODVEND IS NULL)
  AND CAB.CODEMP IN (SELECT EMP.CODEMP AS VALUE
       ,EMP.NOMEFANTASIA AS LABEL
    FROM TSIEMP EMP
ORDER BY 2)
  AND (CAB.STATUSNOTA = 'L' OR :P_CONFIR = 'N')