SELECT SUM(CAB.VLRNOTA) AS VL_NOTAS
     , COUNT(CAB.NUNOTA) AS QTD_NOTA
     , SUM(CAB.VLRNOTA) / COUNT(CAB.NUNOTA) AS TICKET
FROM TGFCAB CAB
WHERE CAB.TIPMOV = 'P' /* P = Pedido de venda */
  AND CAB.DTNEG BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
  AND (CAB.CODVEND = :P_VENDEDOR OR :P_VENDEDOR IS NULL)
  AND (CAB.STATUSNOTA = 'L' OR :P_CONFIR = 'N')
  AND (TO_CHAR(CAB.DTNEG, 'MONTH/YYYY') = :A_MESANO OR :A_MESANO IS NULL)
